### ISSUE TITLE
Rename Section Headers

### ISSUE THREAD

**Issue by mnshukla** [fuzz-productions/FZAccordionTableView#1]
I am having trouble understanding how to change the text for the headers. I just see the .xib file of the headers, but in which file and where can I change the header title?

**Comment by kgaidis** [comment]
Hi there!

I assume you are talking about the Objective-C example. The library is built to not affect how you might lay out your views, so there would never be support for this coming from the library itself.

First, you can always change the text in the `AccordionHeaderView.xib` itself. Nevertheless, if you want to do it in code, or want it to be dynamic, you'll have to add support for it. 

To change the text of the headers in code you can go to `AccordionHeaderView.h` and add in a new property:
`@property (weak, nonatomic) IBOutlet UILabel *titleLabel;`

Then go to the `AccordionHeaderView.xib` file and connect `titleLabel` to the label that's already in the view. You can do this by clicking the top most view ( "Accordion Header View"), tapping "Connections Inspector" and then connecting the 'titleLabel' property to the label.

Then you can go in `FirstViewController.m` and change a method to:

```
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
    AccordionHeaderView *headerView = [tableView dequeueReusableHeaderFooterViewWithIdentifier:kAccordionHeaderViewReuseIdentifier];
    headerView.titleLabel.text = @"New text here";
    return headerView;
}
```

That should do it! Let me know if you have any issues.

**Comment by mnshukla** [comment]
Awesome thanks!
