### ISSUE TITLE
Cells remain Expand

### ISSUE THREAD

**Issue by Gantaios** [fuzz-productions/FZAccordionTableView#12]
Hi i am using your FZAccordionTableView i am using this with segment control each segment control will show different data. the problem is when i select a section it expands until now its fine but without closing the section if i click on next segment the selected section remains opens for the selected segment as well  
i am reloading the table but still can't achieve it .i want it to be closed how can i achieve it 
Help would be great 
 thank you 
![screen shot 2016-05-09 at 4 31 55 pm](https://cloud.githubusercontent.com/assets/18135450/15111333/074033e2-1604-11e6-9c34-49624e0922a4.png)
![screen shot 2016-05-09 at 4 33 25 pm](https://cloud.githubusercontent.com/assets/18135450/15111334/0744a814-1604-11e6-94d5-202a9a4f05c6.png)

**Comment by kgaidis** [comment]
This code would find all the sections that are open and then 'toggle' them, therefore closing them:

```
for (NSInteger i = 0; i < self.tableView.numberOfSections; i++) {
   if ([self.tableView isSectionOpen:i]) {
      [self.tableView toggleSection:i];
   }
}
```

If you'd like to disable the animations:

```
[UIView setAnimationsEnabled:NO];
// Animations happen here
[UIView setAnimationsEnabled:YES];
```

Hope that works. I can foresee some problems with calling `toggleSection` and reloadData at the same time, but we'll see.

**Comment by Gantaios** [comment]
Thanks mate it worked Fine Thank You so much
