### ISSUE TITLE
ImageView Not changing

### ISSUE THREAD

**Issue by Gantaios** [fuzz-productions/FZAccordionTableView#15]
Hi Sorry to disturb you again i have placed a imageview in the headerView i want to show different images when section is opened and closed.But it seems to be not happening any help would be great
here is my code
and that too i want to change only the current expanded section 
- (void)tableView:(FZAccordionTableView *)tableView didOpenSection:(NSInteger)section withHeader:(UITableViewHeaderFooterView *)header
  {
  headerViewC.arrowImageView.image=[UIImage imageNamed:@"CollapseArrow.png"];
  [tableViewAccord addSubview:segmentedControl1];
  NSLog(@"OPENED");
  }
- (void)tableView:(FZAccordionTableView *)tableView didCloseSection:(NSInteger)section withHeader:(UITableViewHeaderFooterView *)header
  {
  
  headerViewC.arrowImageView.image=[UIImage imageNamed:@"ExpandArrow.png"];
  [tableViewAccord shouldPositionParallaxHeader];
  NSLog(@"CLOSED");

}

**Comment by kgaidis** [comment]
I'd just like to note that this is more of a StackOverflow question than an issue with `FZAccordionTableView`, so before opening an issue on GitHub, you should confirm that there's a bug with `FZAccordionTableView` and not your code. 

You should be using the header that is passed to the function: `header`, I don't know what `headerViewC` is. If you are using the `header`, then make sure that the `arrowImageView` is connected correctly, and then make sure that the `UIImage` exists. The latter 2 can be tested independently of using delegate functions of `FZAccordionTableView`.

```
- (void)tableView:(FZAccordionTableView *)tableView didCloseSection:(NSInteger)section withHeader:(UITableViewHeaderFooterView *)header {
   MyCustomHeader *customHeader = (MyCustomHeader *)header;
   customHeader.arrowImageView.image=[UIImage imageNamed:@"ExpandArrow.png"];
   MyCustomTableView *customTableView = (MyCustomTableView *)tableView;
   [customTableView shouldPositionParallaxHeader];
}
```

**Comment by Gantaios** [comment]
headerViewC is an object which i created using your AccordionHeaderView class and the imageview is properly connected but still not working
in between sorry mate i don't how to use github am new to it sorry really
