### ISSUE TITLE
UITableVIew separator becomes invisible 

### ISSUE THREAD

**Issue by harshvishu** [fuzz-productions/FZAccordionTableView#16]
The separator for the tableview sections becomes invisible when a section above is expanded.
If I collapse/expand section 1 the separator between section 1 & section 2 goes away. To get the separator back I have to expand section 2.

**Comment by kgaidis** [comment]
Apologize for the long delay on response. I don't think sections have separators, only cells? Either way, `FZAccordionTableView` does not handle the appearance of how a `UITableView` looks like, it merely provides functionality. If there are any bugs with separators appearing / disappearing, it's probably a `UITableView` issue.

**Comment by harshvishu** [comment]
Got it. Thanks for the help.
