### ISSUE TITLE
Crash when only last section is visible and tapped to close

### ISSUE THREAD

**Issue by tallandy** [fuzz-productions/FZAccordionTableView#17]
If you have a lot of section items and drag the whole tableview so that only the last section is visible and attempt to close it crashes.

<img width="340" alt="screenshot 2016-06-18 22 20 44" src="https://cloud.githubusercontent.com/assets/417628/16173753/45f2b02e-35a3-11e6-9dac-a98a23252399.png">

I've replicated in the example project and in my own project.

`2016-06-18 22:20:21.886 FZAccordionTableViewExample[19251:319019] *** Assertion failure in -[UITableViewRowData rectForHeaderInSection:heightCanBeGuessed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UITableViewRowData.m:1746
2016-06-18 22:20:21.892 FZAccordionTableViewExample[19251:319019] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for rect of header in invalid section (4)'
*** First throw call stack:
(
    0   CoreFoundation                      0x00b07494 __exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x005c1e02 objc_exception_throw + 50
    2   CoreFoundation                      0x00b0732a +[NSException raise:format:arguments:] + 138
    3   Foundation                          0x0023d322 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
    4   UIKit                               0x01b849e2 -[UITableViewRowData rectForHeaderInSection:heightCanBeGuessed:] + 244
    5   UIKit                               0x0191c608 -[UITableView rectForHeaderInSection:] + 89
    6   FZAccordionTableViewExample         0x000d9592 -[FZAccordionTableView sectionForHeaderView:] + 274
    7   FZAccordionTableViewExample         0x000d9b1b -[FZAccordionTableView tappedHeaderView:] + 379
    8   FZAccordionTableViewExample         0x000d8135 -[FZAccordionTableViewHeaderView touchedHeaderView:] + 117
    9   UIKit                               0x01d45d04 _UIGestureRecognizerSendTargetActions + 168
    10  UIKit                               0x01d41bc2 _UIGestureRecognizerSendActions + 176
    11  UIKit                               0x01d3f6c0 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 929
    12  UIKit                               0x01d423b3 -[UIGestureRecognizer _delayedUpdateGesture] + 60
    13  UIKit                               0x01d48cfc ___UIGestureRecognizerUpdate_block_invoke898 + 86
    14  UIKit                               0x01d48b69 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 374
    15  UIKit                               0x01d338a2 _UIGestureRecognizerUpdate + 3407
    16  UIKit                               0x0182eefd -[UIWindow _sendGesturesForEvent:] + 1559
    17  UIKit                               0x018305b6 -[UIWindow sendEvent:] + 1137
    18  UIKit                               0x017d1be8 -[UIApplication sendEvent:] + 266
    19  UIKit                               0x017a6769 _UIApplicationHandleEventQueue + 7795
    20  CoreFoundation                      0x00a19e5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
    21  CoreFoundation                      0x00a0faeb __CFRunLoopDoSources0 + 523
    22  CoreFoundation                      0x00a0ef08 __CFRunLoopRun + 1032
    23  CoreFoundation                      0x00a0e846 CFRunLoopRunSpecific + 470
    24  CoreFoundation                      0x00a0e65b CFRunLoopRunInMode + 123
    25  GraphicsServices                    0x0535e664 GSEventRunModal + 192
    26  GraphicsServices                    0x0535e4a1 GSEventRun + 104
    27  UIKit                               0x017aceb9 UIApplicationMain + 160
    28  FZAccordionTableViewExample         0x000de01a main + 138
    29  libdyld.dylib                       0x03b23a25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by tallandy** [comment]
Possible fix?

```
while (minSection <= maxSection) {
        NSInteger middleSection = (minSection+maxSection)/2;

        // this appears to fix it
       // ******************************
        if (middleSection == maxSection) {
            return maxSection-1;
        }
       // ******************************

        compareHeaderViewFrame = [self rectForHeaderInSection:middleSection];
        if (CGRectEqualToRect(headerViewFrame, compareHeaderViewFrame)) {
            section = middleSection;
            break;
        }
        else if (headerViewFrame.origin.y > compareHeaderViewFrame.origin.y) {
            minSection = middleSection+1;
        }
        else {
            maxSection = middleSection-1;
            section = maxSection; // Occurs when headerView sticks to the top
        }
    }
```

**Comment by kgaidis** [comment]
Thank you for the report! Just confirming that I can replicate the bug and I am looking into it.

**Comment by kgaidis** [comment]
Updated to `0.2.2`. Let me know if this works for you now! I changed up the algorithm to hopefully be more safe and logical. The floating headers make it a little bit tricky.

P.S. Didn't know Github auto-closes issues that were marked in a commit
