### ISSUE TITLE
Swift version of FZAccordionTableView

### ISSUE THREAD

**Issue by SenthilKaliathan** [fuzz-productions/FZAccordionTableView#18]
Hi, 
Thanks for making such great flexible library.  we are looking for pure swift version of "FZAccordionTableView.swift" rather than using bridge header.

Do you have any plans for converting this from objective C to Swift ?

Thanks
Senthil

**Comment by kgaidis** [comment]
Hi there,

Besides having to use the bridging header, what specific issues are you having with the Objective-C file? Or in other words, what would a `.swift` version fix in your case?

**Comment by SenthilKaliathan** [comment]
Hi, 
  Thanks for your reply, We mandate to migrate all the code to .swift version to keep it compatible with project. 
 Other than this I really love this FZAccordionTableView.  I have tried few tools like objectivec2swift.com, But didn't manage to convert 100%.

Thanks,
Senthil

**Comment by kgaidis** [comment]
Closing: converting to pure-Swift code base won't be done until there's a clear need for it.
