### ISSUE TITLE
Crash after quick taps

### ISSUE THREAD

**Issue by igordelorenzi** [fuzz-productions/FZAccordionTableView#2]
The problem happens when I tap a section and, while the animation is still running, quick tap another section.

lldb message:

> **\* Terminating app due to uncaught exception 'NSRangeException', reason: '-[FZAccordionTableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:]: row (0) beyond bounds (0) for section (1).'

The table view is configured as follows:

```
self.tableView.allowMultipleSectionsOpen = NO;
self.tableView.enableAnimationFix = YES;
self.tableView.rowHeight = UITableViewAutomaticDimension;
self.tableView.estimatedRowHeight = 124;
```

**Comment by kgaidis** [comment]
Hi, thanks for reporting!

I cannot reproduce the problem by just setting those settings on device or simulator. Tried iOS 9.2 (device/simulator), 8.1 (simulator).

I used the "Example" in my attempt to recreate the problem with various cell/section counts:
https://github.com/fuzz-productions/FZAccordionTableView/tree/master/Example/Objective-C/FZAccordionTableViewExample

Could you please replicate the problem in that example, and show exactly what you changed to do so?
