### ISSUE TITLE
AccordionTableView crashes after closing the last section 

### ISSUE THREAD

**Issue by xoif** [fuzz-productions/FZAccordionTableView#23]
Thank you for your work on this awesome Accordion. Unfortunately my app crashes in line 216 (        compareHeaderViewFrame = [self rectForHeaderInSection:middleSection];) of FZAccordionTableView.m after trying to close the last Accordion Section. I made the following steps: 
- implemented Accordion View containing 4 sections with custom Header Views
- section 4 is containing several cells. 
- when scrolling down at first the section headers dissapear and then the actual cells in section 4 beginn to scroll. As soon as only section 4 cells are visible, the app crashes when clicking on section 4 header view to close section 4. 
- apart from that, scrolling the last section works fine 
- you can close section 4 if you avoided scrolling section 4 before. 

![simulator screen shot 08 08 2016 17 10 13](https://cloud.githubusercontent.com/assets/7426370/17485106/e81e113e-5d8c-11e6-902c-86de2f99c3e4.png)

`
2016-08-08 16:58:06.312 SBRStarbullsIOS[3965:1797140] *** Assertion failure in -[UITableViewRowData rectForHeaderInSection:heightCanBeGuessed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UITableViewRowData.m:1746`

**Comment by kgaidis** [comment]
Hi thanks for the detailed explanation. Could you provide a full stack trace and iOS version / device tested on?

It's hard to debug without knowing specifics. The best would be to re-create this scenario using the Examples in the "Example" folder. There are infinite possibilities to setup your `UITableView` so I wouldn't be too surprised if one of the setups doesn't work nicely, but it's hard to re-create the failing scenario without actually knowing how to construct it.  

Based off your description it sounds like you have 4 sections, the first 3 sections have no cells, the last section has 4 cells? Then you scroll to the bottom with the last section open and closing it will crash it?

**Comment by kgaidis** [comment]
Also, make sure to be using the latest `FZAccordionTableView` as there were some known bugs with that function before

**Comment by xoif** [comment]
Updating from 0.2.1 to 0.2.2 solved the bug. Thank you for your fast response.

**Comment by kgaidis** [comment]
glad it worked out :)
