### ISSUE TITLE
Select cells in subsections is not working properly

### ISSUE THREAD

**Issue by ahmed-khalil** [fuzz-productions/FZAccordionTableView#3]
After opening any section in the tableview, selecting a cell in the subsection is not responsive at first time. Then, all cells are mixed up and they all point at wrong indexpath.row

To reproduce:
Add the didDeselectRowAtIndexPath delegate function in the firstviewcontroller.m file in the example provided
- (void)tableView:(UITableView *)tableView didDeselectRowAtIndexPath:(NSIndexPath *)indexPath {
  
  NSLog(@"%d", indexPath.row);
  }

Any solution to that issue?!

**Comment by kgaidis** [comment]
Hi there,

So I tested the Example just now and `didSelect` and `didDeselect` work as expected.

You maybe are mixing up the behavior of `didSelect` and `didDeselect`.

`didDeselect` will be called for the row that you last selected, not the row you just selected. So this explains the "not responsive at first time" - you had no cells that were selected.

Let me know.
