### ISSUE TITLE
Retro-comaptiblity

### ISSUE THREAD

**Issue by kristiyanP** [fuzz-productions/FZAccordionTableView#30]
Until which version is this library retro-compatible?

**Comment by kgaidis** [comment]
@kristiyanP do you mean which is the oldest iOS version the library supports?

As Podspec indicates, should be iOS 7.0:
`s.platform     = :ios, '7.0'`
 https://github.com/fuzz-productions/FZAccordionTableView/blob/master/FZAccordionTableView.podspec

However, the backward compatibility is not very well tracked. Something that probably should be done more, but in the common case, the library isn't really dependent upon some special, new features, it's just logic applied on top of `UITableView` so it should be compatible with many older versions.

**Comment by kristiyanP** [comment]
Ok then i am facing a strange behaviour as when i try it on an iOS 9, all the contents inside a cell are not touchable ( i have some buttons inside the cell but their tap event is never triggered )
on iOS 10 and later it works perfectly well

**Comment by kgaidis** [comment]
@kristiyanP 

The cells or the header? 

I could potentially see some problems with header events

**Comment by kristiyanP** [comment]
Inside the cells
When i tap on the header it opens normally the cell, the only issue is that the content of the cell is not user interactable

**Comment by kgaidis** [comment]
ok thank you for the report, I will test or iOS 9 as soon as possible. 

On a first glance, I find the bug to be quite weird because `FZAccordionTableView` doesn't modify or do anything with the cells besides adding and deleting them, so it might be something else.

**Comment by kgaidis** [comment]
If you have sample code _or_ can show the exact steps to recreate the bug using the sample code in this repo, then that would be helpful

**Comment by kgaidis** [comment]
So to the FirstViewController in Obj-C example I added the following:
```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kTableViewCellReuseIdentifier forIndexPath:indexPath];
    UIButton *newButton = [UIButton new];
    newButton.frame = CGRectMake(0, 0, 44, 44);
    [cell.contentView addSubview:newButton];
    [newButton addTarget:self action:@selector(pressedButton:) forControlEvents:UIControlEventTouchUpInside];
    newButton.backgroundColor = [UIColor redColor];
    cell.textLabel.text = @"Cell";
    return cell;
}

- (void)pressedButton:(UIButton *)button
{}
```

I tested on iPhone 6 (9.0) simulator and the button press worked fine (meaning that the content is user interactable).
