### ISSUE TITLE
Multiple levels

### ISSUE THREAD

**Issue by JuanFcoMiranda** [fuzz-productions/FZAccordionTableView#31]
Hi, is there any way to have nested accordions??

Thanks in advance.

**Comment by kgaidis** [comment]
You can if you create a cell, insert another accordion table view in it, and make sure to manage the height changes. The library is a pretty light wrapper around `UITableView` which allows it to be simple and familiar, but it doesn't extend much past the `UITableView` behavior.

For that it sounds like this would be better:
https://github.com/Augustyniak/RATreeView
