### ISSUE TITLE
How to disable all animation ?

### ISSUE THREAD

**Issue by duongsavvycom** [fuzz-productions/FZAccordionTableView#33]
How can we disable all animations open/close from your lib?

**Comment by kgaidis** [comment]
It would require some experimentation but the answer should be no different than the answer to: "How do you disable animations for UITableView insertion / deletion of the cells?"

I would try subclassing, then overriding `insertRowsAtIndexPaths` / `deleteRowsAtIndexPaths` and passing `None` for animations. If that doesn't work I'd try wrapping those calls with techniques to disable / remove animations (there are lots of answers on StackOverflow).
