### ISSUE TITLE
Is there any way collapse all expanded section?

### ISSUE THREAD

**Issue by FredLopes0203** [fuzz-productions/FZAccordionTableView#34]
I want to collapse all sections when I reload data.
When I reload data, expanded section still remain.
Please help me if you have any suggestion.

**Comment by kgaidis** [comment]
I think if you use the following two methods it should work:
`- (BOOL)isSectionOpen:(NSInteger)section;`
`- (void)toggleSection:(NSInteger)section;`

So iterate through all secitons, and if the section is open, close it by calling `toggleSection:`. 

You probably have to wrap the loop in:
`self.tableView.beginUpdates()`
`self.tableView.endUpdates()`

**Comment by FredLopes0203** [comment]
Thanks for your reply.
I'll try.
