### ISSUE TITLE
Tableview Header text color & content view color change

### ISSUE THREAD

**Issue by nileshordex** [fuzz-productions/FZAccordionTableView#36]
Hello Team,
Any one help me for Tableview Header Text Color change and content view Background color change when collapse and expanding header time, means open section or close section time.

**Comment by kgaidis** [comment]
You just want to use the custom `FZAccordionTableViewDelegate` methods:

As a quick example: 
```
func tableView(_ tableView: FZAccordionTableView, willOpenSection section: Int, withHeader header: UITableViewHeaderFooterView?) {
        if let header = header {
            UIView.animate(withDuration: 0.25, animations: {
                header.contentView.backgroundColor = UIColor.red
            })
        }
    }
    
    func tableView(_ tableView: FZAccordionTableView, willCloseSection section: Int, withHeader header: UITableViewHeaderFooterView?) {
        if let header = header {
            UIView.animate(withDuration: 0.25, animations: {
                header.contentView.backgroundColor = UIColor.blue
            })
        }
    }
```

Then make sure that in `func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {` the correct colors are also represented for open/close section.

**Comment by nileshordex** [comment]
Thank a lots Kgaidis, 
I need to objective-c solution am not using swift language.

**Comment by nileshordex** [comment]
@kgaidis ,
Thanks for your reply.
