### ISSUE TITLE
Setting the background color

### ISSUE THREAD

**Issue by ValeriyJefimov** [fuzz-productions/FZAccordionTableView#37]
Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.

**Comment by kgaidis** [comment]
@Bubcagop hello, what about this?

**Comment by ValeriyJefimov** [comment]
Hi, that is the warning that appears in the console if you set the color of the background from the storyboard. It's probably worth changing the background color setting. It's impossible to change the background color of the header from the storyboard

**Comment by kgaidis** [comment]
Oh I guess this is an issue in the example? If I understand correctly, this is not an issue with `FZAccordionTableView` library itself? Either way, thank you for the report I'll look into fixing that!

**Comment by kgaidis** [comment]
I didn't see the warning anymore anywhere so closing
