### ISSUE TITLE
Random insensitivity when opening section header

### ISSUE THREAD

**Issue by VincentV89** [fuzz-productions/FZAccordionTableView#41]
Hi,

Would kindly like to request for help regards to opening of sections. I have 5 sections and randomly the 3rd section isnt sensitive at times. I need to tap below the section view in order to open it. Do you have any advise for this?

Thanks again for this great library !

**Comment by kgaidis** [comment]
@VincentV89 

I'm not sure, do you by chance have example code, video or even better, an example where the bug is reproducible?
