### ISSUE TITLE
Closed all opened sections onces.

### ISSUE THREAD

**Issue by tiwari1amrit** [fuzz-productions/FZAccordionTableView#42]
I want to close all the opened sections?

**Comment by kgaidis** [comment]
@tiwariammit 

Look at: 
https://github.com/fuzz-productions/FZAccordionTableView/issues/34

**Comment by kgaidis** [comment]
Also:
https://github.com/fuzz-productions/FZAccordionTableView/issues/35

**Comment by tiwari1amrit** [comment]
thanks, solved problem
