### ISSUE TITLE
Cells appearing above section header view at start and end of animation

### ISSUE THREAD

**Issue by leeprobert** [fuzz-productions/FZAccordionTableView#43]
I am seeing a glitch with the animations of cells as sections are opened and closed. I've noticed you haven't committed anything to this framework for a while, so I am wondering if this may have anything to do with iOS 10.3 >

UPDATE: I can see the issue. The cells are appearing and disappearing above the section header view.

**Comment by kgaidis** [comment]
@leeprobert 

If you have a video that would be useful.

It may be a new issue, but the animations are definitely not perfect. They are the default that `UITableView` uses. For the most part, the library should function quite well from one iOS version to another as it's just a wrapper. 

If you spot major differences from one iOS version to another, I'd be glad to look at it, but my initial thought is that this might be just how `UITableView` animates.

**Comment by leeprobert** [comment]
Can you confirm that your subclass works using IB and Prototype Cells? Your sample code works ok, but I have noticed that you are creating your cells programmatically. I am using IB and setting the class type on the tableview. The cells are prototypes.

**Comment by leeprobert** [comment]
I did a video for you to look at: https://www.dropbox.com/s/rg2fi74atn1jdyk/accordion.MOV.zip?dl=0

You can see that the cells appear to be animating in and out over the top of the section header views. This doesn't happen with your sample code.

**Comment by kgaidis** [comment]
@leeprobert 

I am not aware of any IB issues (but doesn't mean there aren't any). 

It seems like the issue in the video is that the header might be transparent.

**Comment by kgaidis** [comment]
@leeprobert 

https://stackoverflow.com/questions/15604900/uitableviewheaderfooterview-unable-to-change-background-color

**Comment by leeprobert** [comment]
Yep. That was it. Sorry to bother you. :-)
