### ISSUE TITLE
Is it possible to open another child cell when selecting a cell

### ISSUE THREAD

**Issue by reenaphilip** [fuzz-productions/FZAccordionTableView#48]
I have requirement to show/open a child cell when selecting a cell. Is it possible to implement with this library ?

**Comment by kgaidis** [comment]
Hi @reenaphilip 

This might be the same as the following issue: https://github.com/fuzz-productions/FZAccordionTableView/issues/31

You may want to check out https://github.com/Augustyniak/RATreeView library

If I understood correctly, you could accomplish this with `FZAccordionTableView` if you added another `FZAccordionTableView` within the cell. But that may require a little bit of code to set up as you would need to smartly refresh sizing of the cell

**Comment by reenaphilip** [comment]
Yes . thats the requirement. 
Thanks for the update. I will try.
