### ISSUE TITLE
Implementing multiple levels

### ISSUE THREAD

**Issue by akseli** [fuzz-productions/FZAccordionTableView#50]
I've successfully implemented a few FZAccordionTableViews in our App, but we've come up with the need to add a second "level".

That is, what we're looking to accomplish is:

HEADER (expandable)
--- SUB HEADER (expandable)
-------- ROW (non-expandable)

Is this a feature/functionality that could possibly be added ? 
If anyone has any ideas/pointers, I'd be happy to implement the solution myself, but I'm at a bit of a loss as to where to start.

**Comment by kgaidis** [comment]
`FZAccordionTableView` is meant to be a simple wrapper around `UITableView`, to do multiple levels see the following issue: https://github.com/fuzz-productions/FZAccordionTableView/issues/48

**Comment by akseli** [comment]
Thank you so much @kgaidis !! I don't know how I missed that post!!
