### ISSUE TITLE
header cell not getting full width

### ISSUE THREAD

**Issue by JulienSanfilippo** [fuzz-productions/FZAccordionTableView#8]
<img width="487" alt="capture d ecran 2016-04-20 a 16 31 08" src="https://cloud.githubusercontent.com/assets/9976555/14678297/69187780-0715-11e6-9cba-66abbae2242d.png">

as shown in picture the header cell not take all the width and stay with 320 px , how can i make it dynamic ?
because if i change in xib the size it will not fit in other devices

thanks

**Comment by kgaidis** [comment]
So this is not related to the library itself. 

Are you using auto layout?

**Comment by kgaidis** [comment]
I would look at the Example and try to replicate how the .xib is made there.

The Header View .xib in the example seems to scale just fine on various devices.

**Comment by JulienSanfilippo** [comment]
hi, i have solved the probleme i was using a tableview cell in my xib instead of a regular view like you did on your project , now its properly scaled , thanks
